// src/views/common/mouse-movement/Circle.tsx
'use client'
import { useEffect, useRef, useState } from 'react'
import CSS from './_css/circle.module.css'

export default function Circle() {
  const circleElement = useRef<HTMLDivElement>(null)
  const [circleStyle, setCircleStyle] = useState<{
    left: string
    top: string
  }>({ left: '0px', top: '0px' })

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (!circleElement.current) return
      setTimeout(() => {
        setCircleStyle({
          left: `${e.clientX}px`,
          top: `${e.clientY}px`
        })
      }, 100)
    }

    document.addEventListener('mousemove', handleMouseMove)

    return () => document.removeEventListener('mousemove', handleMouseMove)
  }, [])

  return <div className={CSS.circle} ref={circleElement} style={circleStyle} />
}

// src/views/common/layout/lib/Circle.svelte
<script lang="ts">
	import { onDestroy, onMount } from 'svelte';

	let circleElement: HTMLDivElement | null = null;

	const handleMouseMove = (e: MouseEvent) => {
		if (!circleElement) return;
		setTimeout(() => {
			circleElement.style.left = `${e.clientX}px`;
			circleElement.style.top = `${e.clientY}px`;
		}, 100);
	};

	onMount(() => {
		if (!circleElement || !document) return;
		document.addEventListener('mousemove', handleMouseMove);
	});

	onDestroy(() => {
		if (!circleElement || !document) return;
		document.removeEventListener('mousemove', handleMouseMove);
	});
</script>
<div class="circle" bind:this={circleElement}></div>


<style>
    .circle {
        position: absolute;
        width: 20px;
        height: 20px;
        background-color: transparent;
        border-radius: 50%;
        pointer-events: none;
        border: 2px solid #5e5e5e;
        mix-blend-mode: difference;
        z-index: 100;
        transform: translate(-50%, -50%);
    }
</style>
